-- V1.65: Advanced Training participants may reserve held boats only for their signed-up session window.
create or replace function public.available_boat_ids_for_window(p_start_time timestamptz, p_end_time timestamptz, p_boat_class_id text default null)
returns table(id uuid) language sql stable security definer set search_path = public as $$
  with me as (select p.id, p.skill_level, p.weight_class, p.membership_type from public.profiles p where p.id = auth.uid() and p.status = 'active')
  select b.id from public.boats b join me on true where b.status = 'available' and public.skill_level_to_clearance(me.skill_level) >= b.required_clearance and public.skill_level_rank(me.skill_level) >= public.skill_level_rank(b.required_skill_level) and (b.weight_class is null or public.weight_class_rank(b.weight_class) >= public.weight_class_rank(me.weight_class)) and p_end_time > p_start_time and (p_boat_class_id is null or b.boat_class_id = p_boat_class_id) and not public.boat_in_program_lineup_window(b.id,p_start_time,p_end_time) and not exists (select 1 from public.reservations r where r.boat_id=b.id and r.status in ('reserved','checked_out') and tstzrange(r.start_time,r.end_time,'[)') && tstzrange(p_start_time,p_end_time,'[)')) and not exists (select 1 from public.boat_availability_blocks blk where blk.is_active and public.availability_block_overlaps(blk,p_start_time,p_end_time) and (blk.applies_to_membership_type is null or blk.applies_to_membership_type=me.membership_type) and (blk.applies_to_boat_class_id is null or blk.applies_to_boat_class_id=b.boat_class_id)) and not exists (select 1 from public.training_boat_holds h join public.sessions s on s.id = h.session_id where h.boat_id = b.id and s.session_type = 'coached_training_advanced' and s.is_cancelled = false and tstzrange(h.starts_at,h.ends_at,'[)') && tstzrange(p_start_time,p_end_time,'[)') and not exists (select 1 from public.session_signups ss where ss.session_id = h.session_id and ss.member_id = me.id));
$$;

create or replace function public.can_user_reserve_boat(p_user_id uuid, p_boat_id uuid, p_start_time timestamptz, p_end_time timestamptz)
returns boolean language sql stable security definer set search_path = public as $$
  select p_end_time > p_start_time and not public.boat_in_program_lineup_window(p_boat_id,p_start_time,p_end_time) and exists (select 1 from public.profiles p join public.boats b on b.id=p_boat_id where p.id=p_user_id and p.status='active' and b.status='available' and public.skill_level_to_clearance(p.skill_level)>=b.required_clearance and public.skill_level_rank(p.skill_level)>=public.skill_level_rank(b.required_skill_level) and (b.weight_class is null or public.weight_class_rank(b.weight_class)>=public.weight_class_rank(p.weight_class)) and not exists (select 1 from public.boat_availability_blocks blk where blk.is_active and public.availability_block_overlaps(blk,p_start_time,p_end_time) and (blk.applies_to_membership_type is null or blk.applies_to_membership_type=p.membership_type) and (blk.applies_to_boat_class_id is null or blk.applies_to_boat_class_id=b.boat_class_id)) and not exists (select 1 from public.training_boat_holds h join public.sessions s on s.id = h.session_id where h.boat_id = b.id and s.session_type = 'coached_training_advanced' and s.is_cancelled = false and tstzrange(h.starts_at,h.ends_at,'[)') && tstzrange(p_start_time,p_end_time,'[)') and not exists (select 1 from public.session_signups ss where ss.session_id = h.session_id and ss.member_id = p_user_id)));
$$;

create or replace function public.reserve_boat(p_boat_id uuid, p_start_time timestamptz, p_end_time timestamptz, p_checkout_location text default null, p_notes text default null, p_crew uuid[] default '{}')
returns uuid language plpgsql security definer set search_path = public as $$
declare v_reservation_id uuid; v_seats int; v_crew_count int;
begin
  if exists (select 1 from public.training_boat_holds h join public.sessions s on s.id = h.session_id where h.boat_id = p_boat_id and s.session_type = 'coached_training_advanced' and s.is_cancelled = false and tstzrange(h.starts_at,h.ends_at,'[)') && tstzrange(p_start_time,p_end_time,'[)') and not exists (select 1 from public.session_signups ss where ss.session_id = h.session_id and ss.member_id = auth.uid())) then raise exception 'Boat is held for Advanced Training during this time.'; end if;
  if not public.can_user_reserve_boat(auth.uid(), p_boat_id, p_start_time, p_end_time) then raise exception 'Reservation blocked: member, dues, waiver, clearance, or boat eligibility check failed'; end if;
  if exists (select 1 from public.reservations r where r.created_by = auth.uid() and r.status in ('reserved','checked_out') and tstzrange(r.start_time - interval '90 minutes',r.end_time + interval '90 minutes','[)') && tstzrange(p_start_time,p_end_time,'[)')) then raise exception 'You already have another active or reserved outing within 90 minutes of this time.'; end if;
  select bc.seats into v_seats from public.boats b join public.boat_classes bc on bc.id = b.boat_class_id where b.id = p_boat_id;
  v_crew_count := coalesce(array_length(p_crew, 1), 0);
  if (v_crew_count + 1) > v_seats then raise exception 'Too many crew members for this boat class'; end if;
  insert into public.reservations (boat_id, created_by, start_time, end_time, checkout_location, notes, status) values (p_boat_id, auth.uid(), p_start_time, p_end_time, p_checkout_location, p_notes, 'reserved') returning id into v_reservation_id;
  insert into public.reservation_crew (reservation_id, member_id, seat) values (v_reservation_id, auth.uid(), 'seat1') on conflict do nothing;
  insert into public.reservation_crew (reservation_id, member_id, seat) select v_reservation_id, member_id, null from (select distinct unnest(p_crew) as member_id) x where member_id is not null and member_id <> auth.uid() on conflict do nothing;
  return v_reservation_id;
end;
$$;

drop function if exists public.unavailable_boats_for_window(timestamptz, timestamptz, text);
create or replace function public.unavailable_boats_for_window(p_start_time timestamptz, p_end_time timestamptz, p_boat_class_id text default null)
returns table(boat_id uuid, reservation_status text, expected_return_at timestamptz, availability_title text)
language sql stable security definer set search_path = public as $$
  with me as (select p.id, p.skill_level, p.weight_class, p.membership_type from public.profiles p where p.id = auth.uid() and p.status = 'active'), eligible_boats as (select b.id, b.boat_class_id from public.boats b join me on true where b.status='available' and public.skill_level_to_clearance(me.skill_level)>=b.required_clearance and public.skill_level_rank(me.skill_level)>=public.skill_level_rank(b.required_skill_level) and (b.weight_class is null or public.weight_class_rank(b.weight_class)>=public.weight_class_rank(me.weight_class)) and (p_boat_class_id is null or b.boat_class_id=p_boat_class_id)), reasons as (
    select r.boat_id, r.status::text as reservation_status, r.end_time as expected_return_at, null::text as availability_title, case when r.status = 'checked_out' then 1 else 2 end as priority from public.reservations r join eligible_boats b on b.id=r.boat_id where r.status in ('reserved','checked_out') and tstzrange(r.start_time,r.end_time,'[)') && tstzrange(p_start_time,p_end_time,'[)')
    union all select b.id, 'availability_block'::text, null::timestamptz, blk.title, 3 from eligible_boats b join me on true join public.boat_availability_blocks blk on blk.is_active and public.availability_block_overlaps(blk,p_start_time,p_end_time) and (blk.applies_to_membership_type is null or blk.applies_to_membership_type=me.membership_type) and (blk.applies_to_boat_class_id is null or blk.applies_to_boat_class_id=b.boat_class_id)
    union all select b.id, 'training_hold'::text, h.ends_at, coalesce(s.title, 'Advanced Training'), 4 from eligible_boats b join me on true join public.training_boat_holds h on h.boat_id = b.id join public.sessions s on s.id = h.session_id where s.session_type = 'coached_training_advanced' and s.is_cancelled = false and tstzrange(h.starts_at,h.ends_at,'[)') && tstzrange(p_start_time,p_end_time,'[)') and not exists (select 1 from public.session_signups ss where ss.session_id = h.session_id and ss.member_id = me.id)
  ) select distinct on (boat_id) boat_id, reservation_status, expected_return_at, availability_title from reasons order by boat_id, priority;
$$;
revoke all on function public.unavailable_boats_for_window(timestamptz, timestamptz, text) from public;
grant execute on function public.unavailable_boats_for_window(timestamptz, timestamptz, text) to authenticated;

-- Keep the Advanced publisher as the final safeguard against duplicate editable-seat assignments.
create or replace function public.publish_advanced_training_held_lineup(p_lineup_board_id uuid, p_assignments jsonb)
returns table(member_id uuid, old_boat_name text, new_boat_name text, session_title text)
language plpgsql security definer set search_path = public as $$
declare v_session record; v_boat record; v_reservation record; v_member record; v_reconciliations jsonb;
begin
  if not public.can_manage_club_data() then raise exception 'Only a coach or manager can publish Advanced Training lineups'; end if;
  select s.id, s.title, s.starts_at, s.ends_at, s.session_type, s.is_cancelled into v_session from public.lineup_boards lb join public.sessions s on s.id = lb.session_id where lb.id = p_lineup_board_id for update of lb, s;
  if v_session.id is null or v_session.session_type <> 'coached_training_advanced' or v_session.is_cancelled then raise exception 'This lineup is not an active Advanced Training session'; end if;
  perform 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id for update;
  update public.lineup_seats ls set member_id = input."memberId" from jsonb_to_recordset(p_assignments) as input("seatId" uuid, "memberId" uuid), public.lineup_boats lb where ls.id = input."seatId" and lb.id = ls.lineup_boat_id and lb.lineup_board_id = p_lineup_board_id;
  if exists (select 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and ls.member_id is not null group by ls.member_id having count(*) > 1) then raise exception 'A rower can only be assigned to one seat in this lineup.'; end if;
  if exists (select 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and ls.member_id is not null and not exists (select 1 from public.session_signups ss where ss.session_id = v_session.id and ss.member_id = ls.member_id)) then raise exception 'A lineup rower is not signed up for this Advanced Training session'; end if;
  for v_boat in select lb.fleet_boat_id, lb.boat_name from public.lineup_boats lb where lb.lineup_board_id = p_lineup_board_id and lb.fleet_boat_id is not null loop
    if not exists (select 1 from public.boats b where b.id = v_boat.fleet_boat_id and b.status = 'available') then raise exception '% is no longer operational', v_boat.boat_name; end if;
    if not exists (select 1 from public.training_boat_holds h where h.session_id = v_session.id and h.boat_id = v_boat.fleet_boat_id and tstzrange(h.starts_at,h.ends_at,'[)') @> tstzrange(v_session.starts_at,v_session.ends_at,'[)')) then raise exception '% is not held for this Advanced Training session', v_boat.boat_name; end if;
    if not exists (select 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and lb.fleet_boat_id = v_boat.fleet_boat_id and ls.member_id is not null) then raise exception '% needs at least one assigned rower before publishing', v_boat.boat_name; end if;
    select r.id, r.status, r.created_by into v_reservation from public.reservations r where r.boat_id = v_boat.fleet_boat_id and r.status in ('reserved','checked_out') and tstzrange(r.start_time,r.end_time,'[)') && tstzrange(v_session.starts_at,v_session.ends_at,'[)') for update;
    if found and v_reservation.status = 'checked_out' then raise exception '% is already checked out and cannot be used for Advanced Training', v_boat.boat_name; end if;
    if found and (not exists (select 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and lb.fleet_boat_id = v_boat.fleet_boat_id and ls.member_id = v_reservation.created_by) or exists (select 1 from public.reservation_crew rc where rc.reservation_id = v_reservation.id and not exists (select 1 from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and lb.fleet_boat_id = v_boat.fleet_boat_id and ls.member_id = rc.member_id))) then raise exception '% has an existing member reservation that conflicts with this Advanced Training session. Resolve the reservation conflict before publishing.', v_boat.boat_name; end if;
  end loop;
  for v_member in select distinct ls.member_id, lb.boat_name, lb.fleet_boat_id, b.required_clearance, b.required_skill_level, b.weight_class, p.status, p.skill_level, p.weight_class as member_weight_class from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id join public.boats b on b.id = lb.fleet_boat_id join public.profiles p on p.id = ls.member_id where lb.lineup_board_id = p_lineup_board_id and ls.member_id is not null and lb.fleet_boat_id is not null loop
    if v_member.status <> 'active' then raise exception 'A final lineup member is not active for %', v_member.boat_name; end if;
    if public.skill_level_to_clearance(v_member.skill_level) < v_member.required_clearance then raise exception 'A final lineup member does not meet the required clearance for %', v_member.boat_name; end if;
    if public.skill_level_rank(v_member.skill_level) < public.skill_level_rank(v_member.required_skill_level) then raise exception 'A final lineup member does not meet the required skill level for %', v_member.boat_name; end if;
    if v_member.weight_class is not null and public.weight_class_rank(v_member.weight_class) < public.weight_class_rank(v_member.member_weight_class) then raise exception 'A final lineup member does not meet the weight requirement for %', v_member.boat_name; end if;
  end loop;
  select coalesce(jsonb_agg(jsonb_build_object('reconciliation_member_id', members.member_id, 'action', 'update')), '[]'::jsonb) into v_reconciliations from (select distinct ls.member_id from public.lineup_seats ls join public.lineup_boats lb on lb.id = ls.lineup_boat_id where lb.lineup_board_id = p_lineup_board_id and lb.fleet_boat_id is not null and ls.member_id is not null) members;
  return query select * from public.publish_coached_training_lineup(p_lineup_board_id, '[]'::jsonb, v_reconciliations);
end;
$$;
